---
- hosts: all
  become: true
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
  
  - name: Install Java
    apt:
      name: openjdk-17-jdk
      state: present

  - name: Download Jenkins repository key
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present
    
  - name: Add Jenkins repository to the sources list
    apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/
      state: present
      
  - name: Update apt cache
    apt:
      update_cache: yes
  
  - name: Install Jenkins
    apt:
      name: jenkins
      state: present
      
  - name: Ensure directories exists
    file:
      path: "{{ item.path }}"
      state: directory
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: '0755'
    loop:
      - { path: '/var/lib/jenkins', owner: 'jenkins', group: 'jenkins'}
      - { path: '/var/lib/jenkins/init.groovy.d', owner: 'jenkins', group: 'jenkins'}
      - { path: '/etc/systemd/system/jenkins.service.d', owner: 'root', group: 'root'}
      
  - name: Create jenkins service override file
    copy:
      dest: /etc/systemd/system/jenkins.service.d/override.conf
      content: |
        [Service]
        Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
      mode: '0644'
      
  - name: Reload systemd daemon
    command: systemctl daemon-reload
      
  - name: Copy Groovy scripts to remote machine
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: '0755'
      owner: jenkins
      group: jenkins
    loop:
      - { src: 'JenkinsScripts/1-InstallPlugins.groovy', dest: '/var/lib/jenkins/init.groovy.d/1-InstallPlugins.groovy' }
      - { src: 'JenkinsScripts/2-CreateAdminUser.groovy', dest: '/var/lib/jenkins/init.groovy.d/2-CreateAdminUser.groovy' }
      - { src: 'JenkinsScripts/3-ConfigureSharedPipeline.groovy', dest: '/var/lib/jenkins/init.groovy.d/3-ConfigureSharedPipeline.groovy' }
      - { src: 'JenkinsScripts/4-CreateJob.groovy', dest: '/var/lib/jenkins/init.groovy.d/4-CreateJob.groovy' }

      
  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: restarted
      name: jenkins