---
- hosts: all
  become: true
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
  
  - name: Install Java
    apt:
      name: openjdk-17-jdk
      state: present

  - name: Download Jenkins repository key
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present
    
  - name: Add Jenkins repository to the sources list
    apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/
      state: present
      
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Preconfigure Jenkins to not start automatically
    debconf:
      name: jenkins
      question: jenkins/skip-start
      value: "true"
      vtype: boolean
  
  - name: Install Jenkins
    apt:
      name: jenkins
      state: present
  
  - name: Ensure /var/jenkins_home exists
    file:
      path: /var/jenkins_home
      state: directory
      owner: jenkins
      group: jenkins
      mode: '0755'
      
  - name: Create directory for Jenkins Groovy init scripts
    file:
      path: /var/lib/jenkins/init.groovy.d
      state: directory
      owner: jenkins
      group: jenkins
      mode: '0755'
      
  - name: Copy 1 script to remote machine
    copy:
      src: JenkinsScripts/1-InitializeInstance.groovy
      dest: /var/lib/jenkins/init.groovy.d/1-InitializeInstance.groovy
      mode: '0755'
      owner: jenkins
      group: jenkins
      
  - name: Copy script to remote machine
    copy:
      src: JenkinsScripts/2-CreateAdminUser.groovy
      dest: /var/lib/jenkins/init.groovy.d/2-CreateAdminUser.groovy
      mode: '0755'
      owner: jenkins
      group: jenkins
  
  - name: Copy 3 script to remote machine
    copy:
      src: JenkinsScripts/1-InitializeInstance.groovy
      dest: /var/lib/jenkins/init.groovy.d/3-InstallPlugins.groovy
      mode: '0755'
      owner: jenkins
      group: jenkins