name: Must run on custom runner

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: list dir
        run: |
          ls
          pwd
          aws --help
